### ISSUE TITLE
Bug while expanding

### ISSUE THREAD

**Issue by edurante** [abo-abo/auto-yasnippet#11]
Hi,

I don't know if this is the right behavior but the following two snippets don't expand correctly
(tested in C++ mode, some text is missing after the expansion)

class ~1Render: public ~2RenderBase;
class Klm~1Render: public Klm~2RenderBase;

However, the following snippet expands in the right manner

class Render~1: public RenderBase~2;

Thanks for this very useful tool
edurante

**Comment by abo-abo** [comment]
I don't really understand why you're using digits here: C++ identifiers can't start with a digit.

But the problem with the first snippet is that `1Render` is considered to be a full symbol name, so it's replaced as a whole. There really isn't a great way around this, but you could try this approach:

    class `Triangle'Render: public TriangleRenderBase;

It allows to enter:

    class CircleRender: public CircleRenderBase;

with just `Circle`. This method only works if you have a single field that needs to be copied. It works either for a single line or for a region.

**Comment by edurante** [comment]
Now I understand. I thought that a field was defined according to the syntax ~[1-9]. You are telling me that a field is the text that follows ~ up to a punctuation symbols or a whitespace. For the following snippets:

class Klm~1Render: public Klm~2RenderBase;

The two fields are 1Render and 2RenderBase. Every occurence of these two fields will be replaced at expansion time. This way we can reuse an existing code and put ~ where we want the text be replaced.

Thanks for the tricks
class `Triangle'Render: public TriangleRenderBase;
it works well.

Best
edurante
