### ISSUE TITLE
Document midword expansion

### ISSUE THREAD

**Issue by Wilfred** [abo-abo/auto-yasnippet#13]
I had some verbose code:

```python
foo_settings = load_thing("foo.yaml")
bar_settings = load_thing("bar.yaml")
baz_settings = load_thing("baz.yaml")
```

I expected that I could generalise with:

```
~1_settings = load_thing("~1.yaml")
```

based on my understanding of the example given:

```
field~1 = document.getElementById("field~1");
```

[This comment](https://github.com/abo-abo/auto-yasnippet/issues/11#issuecomment-116650865) shows another user assuming the same behaviour that I expected. #12 makes this functionality possible, so the correct approach for my example is:

```
`baz'_settings = load_thing("`baz'.yaml")
```

Could you give an example in the Commentary? I'm happy to have a go at writing an example if you like.

**Comment by abo-abo** [comment]
> I'm happy to have a go at writing an example if you like.

Please do. When I explain things, they sound good in my head, but them people complain:)
