### ISSUE TITLE
cannot use aya-create with multiple lines

### ISSUE THREAD

**Issue by DJJ88** [abo-abo/auto-yasnippet#18]
Hello, 

I tried to use the example 
<C-space>~FooType get~Foo() {
    // Get the ~foo attribute on this.
    return this.~foo;
} <point> <aya-create>
but It didn't produce the expected results.

**Comment by abo-abo** [comment]
This works as expected for me, three fields are produced:

```
"$1 get$2() {
  // Get the $3 attribute on this.
  return this.$3;
}"
```

If you want a more precise control, use this:
```
`Foo'Type get`Foo'() {
  // Get the `foo' attribute on this.
  return this.`foo';
}
```
