### ISSUE TITLE
yas-global-mode in aya-expand

### ISSUE THREAD

**Issue by fice-t** [abo-abo/auto-yasnippet#20]
@abo-abo 
Does it need to be turned on every time, or can it just be turned on once? The inclusion of this in https://github.com/abo-abo/auto-yasnippet/commit/35760e8e06eb2f724fd456ad05b8ddbdf9a51f76 made `aya-expand` a few times slower for me.

Changing it to `(unless yas-global-mode (yas-global-mode)` sped it back up, and it seems to still work.

**Comment by abo-abo** [comment]
Thanks.
