### ISSUE TITLE
Multiple placeholders failed

### ISSUE THREAD

**Issue by smallst** [abo-abo/auto-yasnippet#21]
i try to select a region and exec aya-create as Multiple placeholders shows in Usage, but only cursor line changed, was i misunderstanding how to use Multiple placeholders?

**Comment by abo-abo** [comment]
Works fine for me. Can you eval `aya-current` after you call `aya-create`?

**Comment by smallst** [comment]
i get the `Undeclared variable or function 'count_ofred'` error 
and i have no `aya-current`  function

**Comment by abo-abo** [comment]
I meant <kbd>M-x</kbd> `eval-expression`, enter `aya-current` and <kbd>RET</kbd>.

**Comment by smallst** [comment]
as for 
```
~FooType get~Foo() {
    // Get the ~foo attribute on this.
    return this.~foo;
}
```
when i begin select from first line, aya-current is "}"
when i begin select from last line , aya-current is `"$1 get$2() {"`

**Comment by abo-abo** [comment]
Try to reproduce with `emacs -Q -l yasnippet.el -l auto-yasnippet.el`.

**Comment by smallst** [comment]
same result.
just in case, i think select a  region means C-space for mark set then move cursor ,then i exec aya-create.

**Comment by abo-abo** [comment]
> emacs-24.5 -Q -l yasnippet.el -l auto-yasnippet.el README.md

This works perfectly fine for me:

- x86_64 GNU/Linux
- emacs-24.5
- yasnippet-0.10.0
- auto-yasnippet 20160809.46

**Comment by smallst** [comment]
oh, i use melpa-stable and auto-yasnippet is 0.3.0.
let me try 20160809.46

**Comment by smallst** [comment]
yeah, ver.20160809.46  is ok.
aya-current is 
```
"
$1 get$2() {
    // Get the $3 attribute on this.
    return this.$3;
}"
```
by the way, although there is a white space after $1. but when i use aya-expand, there is no space before 'get$2' , why ?
![screenshot_2016-08-12_22-44-54](https://cloud.githubusercontent.com/assets/11417632/17626102/6758d5de-60de-11e6-8c9b-bb41feefc8c6.png)

**Comment by abo-abo** [comment]
No idea, I have the whitespace.

**Comment by smallst** [comment]
ok.  Thank you very much!

**Comment by smallst** [comment]
oh, i try several times and find when select region contains a blank line before first line, the whitespace will miss, if the select region is exactly, everything is fantastic!
