### ISSUE TITLE
Add snippet saving feature

### ISSUE THREAD

**Issue by tuhdo** [abo-abo/auto-yasnippet#3]
Some snippet is worth saving for future use. It would be nice to have this feature.

**Comment by jasonm23** [comment]
I don't think this really addresses the issue.   Auto-save should be placing a snippet file into the appropriate mode subfolder of the user snippets folder.

This is a little more complicated to implement, but takes all of the leg work away from the user.

I am more than happy to add this feature properly myself.  Please re-open the issue.

**Comment by abo-abo** [comment]
As you wish, send the pull request anytime.

**Comment by abo-abo** [comment]
It seems that this was fixed sometime ago.
