### ISSUE TITLE
Repo/Project activity check.

### ISSUE THREAD

**Issue by jasonm23** [abo-abo/auto-yasnippet#37]
@abo-abo 

Hi Oleh,  I noticed that you haven't been active on this for a few years.  First off, I hope you're ok and well.

As a contributor, I'd like to pick up maintenance of this project.  The pull request #36 provides history features, however I'm also just pushing new changes and edits to other areas of functionality and documentation.  I'll make efforts to keep commits atomic so we can cherry pick.  Whatever the outcome, I take responsibility for cleaning up any amendments.

Key changes.

- History 
    - New `aya-create` snippets are stored in history as well as updating `aya-current`.
    - User can expand any snippet from history.
    - User can delete any snippet from history (`aya-current` will be reset as needed to the most recent snippet) 
- Remove support for backquote/quote arbitrary text markers.
- Escape chars necessary for yasnippet compatibility.
- Provide extended support for adhoc/interactive in-place yasnippet creation
- Documentation
    - Commentary as source of truth 
    - Goal: generate README from Commentary
    - Example Bindings
        -  use `bind-key` to allow a quick prefix map definition.
    - Updating install and setup
    - Other required updates or corrections.

This is a so-far list, I will make efforts to keep a `.plan` file up to date in the repo root on emacsfodder/auto-yasnippet

If you're supportive of the idea, you can transfer ownership of the MELPA recipe to me.

If I don't get response to this I'll reach out to the folks at MELPA at the end of August to see if they can support a transition of maintainer.

(I'll use this thread as a communication center when reaching out to MELPA folks for transparency.)

**Comment by jasonm23** [comment]
@purcell - I'm trying to raise @abo-abo re this issue.

I'm a little uncomfortable assuming maintenance of this project. However, as @abo-abo hasn't been present for a few years (on issues and PRs in the repo.) Is there a procedure / policy on MELPA wrt this sort of situation?

**Comment by jasonm23** [comment]
I think there's enough in #36 to simply create a new package, `ayah` (i.e. _`auto-yasnippet-history`_) that just depends on auto-yasnippet.

**Comment by abo-abo** [comment]
Hi @jasonm23. I'm still around. I haven't had time for Elisp projects because I'm taking care of my son born in 2021. I'm slowly getting back to it. I will add you as a maintainer for this project so that you can merge your and other people's PRs.

**Comment by jasonm23** [comment]
Thank you Oleh & congratulations on the new addition to your family.  Wishing you all the best!
