### ISSUE TITLE
Problem of aya-expand-from-history

### ISSUE THREAD

**Issue by allenryb** [abo-abo/auto-yasnippet#41]
It seems a typos

https://github.com/abo-abo/auto-yasnippet/blob/f54fb424082a68f28d2b86707d9bd1cd506b2d9a/auto-yasnippet.el#L499-L500

should be 

```
(unless (> (length aya-history) 0)
      (user-error "Nothing in aya-history to expand"))
```

**Comment by jasonm23** [comment]
https://github.com/abo-abo/auto-yasnippet/blob/f54fb424082a68f28d2b86707d9bd1cd506b2d9a/auto-yasnippet.el#L490-L502

?

**Comment by jasonm23** [comment]
amending now
