### ISSUE TITLE
Does a snippet need to have at least one marker?

### ISSUE THREAD

**Issue by Tokubara** [abo-abo/auto-yasnippet#42]
I find that I can't create a snippet without markers.
I read the source code of `aya-create` and find that it take actions only when there is at least one marker. So I can't create a snippet without markers, right?

**Comment by jasonm23** [comment]
Please explain why you'd need to?

If you want to repeat a yank/paste for a number of different text items.  Use Emacs built in `copy-to-register` and `C-<register number>` `yank` to paste the specific register
