### ISSUE TITLE
README heading "javascript aya-one-line"

### ISSUE THREAD

**Issue by jasonm23** [abo-abo/auto-yasnippet#8]
https://github.com/abo-abo/auto-yasnippet#javascript---aya-one-line

Should this be a JavaScript specific heading?  It seems that `aya-one-line` is a general feature, not JS specific.

Is that right?

If so, shouldn't the `aya-one-line` description should be up with the other function descriptions, without it's JS heading?

**Comment by jasonm23** [comment]
As usual, happy to make the amendments myself.

**Comment by abo-abo** [comment]
> As usual, happy to make the amendments myself.

You're right, please do.
